version: '3.8'

services:
  kms-crypto:
    build: .
    ports:
      - "9000:9000"
    environment:
      - RUST_LOG=info
      - KMS_SERVER_BIND_ADDRESS=0.0.0.0:9000
    volumes:
      - ./keys:/app/keys
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 