[server]
bind_address = "127.0.0.1:9000"
cors_origins = ["*"]

[storage]
key_store_path = "keys.json"
asymmetric_keys_path = "keys/asymmetric"
backup_enabled = false
backup_path = "backup"

[security]
max_key_size = 4096
max_plaintext_size = 65536
key_expiration_days = 365

[logging]
level = "info"
format = "json" 